### ISSUE TITLE
Giovanna Borges Bottino

### ISSUE THREAD

**Issue by giovannabbottino** [FGA-GCES/Trabalho-Individual-2022-1#1]
Nome: Giovanna Borges Bottino
Matrícula: 170011267
Repositório: https://github.com/giovannabbottino/Trabalho-Individual-2022-1

**Comment by renatocoral** [comment]
| Item                                                     | Nota | Observações                                                                                                                  |
| -------------------------------------------------------- | ---- | ---------------------------------------------------------------------------------------------------------------------------- |
| 1\. Containerização do Banco                             | 1,0  | OK                                                                                                                           |
| 2\. Containerização da Aplicação + Banco                 | 1,5  | OK                                                                                                                           |
| 3\. Containerização da Aplicação + Banco + Front         | 1,5  | OK                                                                                                                           |
| 4\. Containerização da Aplicação + Banco + Front + Nginx | 1,5  | OK                                                                                                                           |
| 5\. Integração Contínua (Build, Test, Lint)              | 2,5  | Implementado, mas o workflow falha no lint                                                                                   |
| 6\. Deploy Contínuo                                      | 0,5  | Como não passou no lint, o deploy não foi realizado em nenhum momento, então não é possível verificar o que foi implementado |
| Total                                                    | 8,5  |                                                                                                                              |
