### ISSUE TITLE
Hérya Rodrigues Alcantara

### ISSUE THREAD

**Issue by hryds** [FGA-GCES/Trabalho-Individual-2022-1#15]
Nome: Hérya Rodrigues Alcantara
Matrícula: 180018574
Repósitorio: https://github.com/hryds/GCES_Trabalho-Individual-2022-1

**Comment by renatocoral** [comment]
| Item                                                     | Nota | Observações       |
| -------------------------------------------------------- | ---- | ----------------- |
| 1\. Containerização do Banco                             | 1,0  | Ok!               |
| 2\. Containerização da Aplicação + Banco                 | 1,5  | Ok!               |
| 3\. Containerização da Aplicação + Banco + Front         | 1,5  | Ok!               |
| 4\. Containerização da Aplicação + Banco + Front + Nginx | 0    | Não implementado! |
| 5\. Integração Contínua (Build, Test, Lint)              | 0,0  | Não implementado! |
| 6\. Deploy Contínuo                                      | 0    | Não implementado! |
| Total                                                    | 4,0  |                   |
