### ISSUE TITLE
Rafael Cleydson da Silva Ramos

### ISSUE THREAD

**Issue by RcleydsonR** [FGA-GCES/Trabalho-Individual-2022-1#39]
Nome: Rafael Cleydson da Silva Ramos
Matrícula: 19/0019085
Repositório: https://github.com/RcleydsonR/Trabalho-Individual-2022-1

[Aplicação backend (heroku)](https://library-back-gces.herokuapp.com/)
[Aplicação frontend (netlify)](https://library-gces.netlify.app/)

**Comment by renatocoral** [comment]
| Item                                                     | Nota | Observações                     |
| -------------------------------------------------------- | ---- | ------------------------------- |
| 1\. Containerização do Banco                             | 1,0  |                                 |
| 2\. Containerização da Aplicação + Banco                 | 1,5  |                                 |
| 3\. Containerização da Aplicação + Banco + Front         | 1,5  |                                 |
| 4\. Containerização da Aplicação + Banco + Front + Nginx | 1,5  |                                 |
| 5\. Integração Contínua (Build, Test, Lint)              | 3,0  |                                 |
| 6\. Deploy Contínuo                                      | 1,5  | Todos os pontos foram entregues |
| Total                                                    | 10,0 |                                 |
