### ISSUE TITLE
João Gabriel de Campos de Matos

### ISSUE THREAD

**Issue by JongaMatos** [FGA-GCES/Trabalho-Individual-2022-1#62]
Nome: João Gabriel de Campos de Matos
Matricula:18/0042238
Professora: Carla
Repositório: https://github.com/JongaMatos/Trabalho-Individual-2022-1

**Comment by renatocoral** [comment]
| Item                                                     | Nota | Observações                             |
| -------------------------------------------------------- | ---- | --------------------------------------- |
| 1\. Containerização do Banco                             | 1,0  | Ok!                                     |
| 2\. Containerização da Aplicação + Banco                 | 1,5  | Ok!                                     |
| 3\. Containerização da Aplicação + Banco + Front         | 1,5  | Ok!                                     |
| 4\. Containerização da Aplicação + Banco + Front + Nginx | 1    | Falta aconfiguração no arquivo do nginx |
| 5\. Integração Contínua (Build, Test, Lint)              | 3,0  | Ok!                                     |
| 6\. Deploy Contínuo                                      | 1,5  | Ok!                                     |
| Total                                                    | 9,5  |                                         |
