### ISSUE TITLE
Matheus Fonseca Sousa 

### ISSUE THREAD

**Issue by gatotabaco** [FGA-GCES/Trabalho-Individual-2022-1#74]
Nome: Matheus Fonseca Sousa
Matrícula:170111059
Professora: Carla

Repositório: https://github.com/gatotabaco/TrabalhoGCES

**Comment by renatocoral** [comment]
| Item                                                     | Nota | Observações                                                                                                                          |
| -------------------------------------------------------- | ---- | ------------------------------------------------------------------------------------------------------------------------------------ |
| 1\. Containerização do Banco                             | 1,0  | Ok!                                                                                                                                  |
| 2\. Containerização da Aplicação + Banco                 | 0,5  | [Falta executar as migrations da base e o path para o arquivo manage.py no command do docker-compose está errado](http://manage.py/) |
| 3\. Containerização da Aplicação + Banco + Front         | 1,5  | Ok!                                                                                                                                  |
| 4\. Containerização da Aplicação + Banco + Front + Nginx | 1,5  | Ok!                                                                                                                                  |
| 5\. Integração Contínua (Build, Test, Lint)              | 2,5  | Erro no stage de Tests                                                                                                               |
| 6\. Deploy Contínuo                                      | 0    | Não implementado                                                                                                                     |
| Total                                                    | 7,0  |                                                                                                                                      |
